# Generated by Django 5.1.1 on 2024-09-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='resumo',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
