# Generated by Django 5.1.1 on 2024-09-16 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_categoria_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='color',
        ),
    ]
