# Generated by Django 5.1.1 on 2024-09-19 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_categoria_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='resumo',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=150),
        ),
    ]
